# Generated by Django 5.2.3 on 2025-07-04 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 4, 15, 2, 15, 581154)),
            preserve_default=False,
        ),
    ]
