# Generated by Django 5.2.3 on 2025-07-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
