# Generated by Django 5.2.3 on 2025-07-04 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_referral_is_approved_referral_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
