# Generated by Django 5.2.3 on 2025-07-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_referral_affiliate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='affiliate',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
